//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullCodeBasedTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblPerson
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Please Enter Name.")]
        public string Name { get; set; }
        [Required, RegularExpression(@"^(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}$", ErrorMessage = "Email Pattern is Invalid.")]
        public string Email { get; set; }
        [Required, MaxLength(12)]        
        public string Mobile { get; set; }
        [Required(ErrorMessage ="Select any course.")]
        public string Course { get; set; }
        [Required(ErrorMessage ="Percentage Field is Required.")]
        public string Percentage { get; set; }
        [Required(ErrorMessage ="Address is Required.")]
        public string Address { get; set; }
        public Nullable<int> City { get; set; }
    
        public virtual TblCity TblCity { get; set; }
    }
}
